baseurl: ''
languageCode: "en-us"
title: "Hotnews Post"
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

disableHugoGeneratorInject: true
pluralizeListTitles: false
minify: true

taxonomies:
    year: "year"
    month: month

permalinks:
  post: /posts/:year/:month/:day/:slug/
  year: /posts/:slug/
  month: /posts/:slug/

menu:
  main:
    - name: Home
      url: "/"
      weight: 1
    - name: About
      url: /about
      weight: 4
    - name: Archive
      identifier: posts
      url: /posts
      weight: 2
    - name: Tags
      url: /tags
      identifier: tags
      weight: 3

params:
  description: "Hotnews is a theme imitating a newspaper,  powered by Hugo."
  FooterText: "© Hotnews Theme"

  # How many articles should be displayed at the frontpage
  paginate: 10

frontmatter:
  author: gitrust
  github: 'https://github.com/gitrust/hugo-hotnews'
  og_image: /images/####
  sitename: ######
  twitter: '######'

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: atom


